spring.datasource.url=jdbc:mysql://localhost:3306/roadrescue?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=3736
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

roadrescue.app.jwtSecret=RoadRescueSecretKeyWhichShouldBeVeryLongToBeSecureEnoughForHS256Algorithm!
roadrescue.app.jwtExpirationMs=86400000

server.port=8081
